-- MySQL Script generated by MySQL Workbench
-- Sun Nov 14 17:13:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(2048) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `creation_date` DATE NOT NULL,
  `visibility` TINYINT NOT NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`historial` ;

CREATE TABLE IF NOT EXISTS `mydb`.`historial` (
  `id_historial` INT NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `exchange_date` DATE NOT NULL,
  `id_proyecto` INT NOT NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `fk_historial_proyecto1_idx` (`id_proyecto` ASC) VISIBLE,
  CONSTRAINT `fk_historial_proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`miembro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`miembro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`miembro` (
  `id_miembro` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `id_proyecto` INT NOT NULL,
  PRIMARY KEY (`id_miembro`),
  INDEX `fk_miembro_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_miembro_rol1_idx` (`id_rol` ASC) VISIBLE,
  INDEX `fk_miembro_proyecto1_idx` (`id_proyecto` ASC) VISIBLE,
  CONSTRAINT `fk_miembro_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembro_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mydb`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembro_proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tarea` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tarea` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `id_proyecto` INT NOT NULL,
  `id_miembro` INT NOT NULL,
  `creation_date` DATE NOT NULL,
  `estado_id_estado` INT NOT NULL,
  PRIMARY KEY (`id_tarea`),
  INDEX `fk_tarea_proyecto1_idx` (`id_proyecto` ASC) VISIBLE,
  INDEX `fk_tarea_miembro1_idx` (`id_miembro` ASC) VISIBLE,
  INDEX `fk_tarea_estado1_idx` (`estado_id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_miembro1`
    FOREIGN KEY (`id_miembro`)
    REFERENCES `mydb`.`miembro` (`id_miembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_estado1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `mydb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`responsable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`responsable` (
  `id_responsable` INT NOT NULL AUTO_INCREMENT,
  `id_tarea` INT NOT NULL,
  `id_miembro` INT NOT NULL,
  PRIMARY KEY (`id_responsable`),
  INDEX `fk_responsable_tarea1_idx` (`id_tarea` ASC) VISIBLE,
  INDEX `fk_responsable_miembro1_idx` (`id_miembro` ASC) VISIBLE,
  CONSTRAINT `fk_responsable_tarea1`
    FOREIGN KEY (`id_tarea`)
    REFERENCES `mydb`.`tarea` (`id_tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsable_miembro1`
    FOREIGN KEY (`id_miembro`)
    REFERENCES `mydb`.`miembro` (`id_miembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`usuario` (`id_usuario`, `username`, `password`, `email`) VALUES (99, 'test', 'test', 'test');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`rol` (`id_rol`, `name`, `description`) VALUES (1, 'Creador', 'Creador del proyecto.');
INSERT INTO `mydb`.`rol` (`id_rol`, `name`, `description`) VALUES (2, 'Editor', 'Tiene permisos para gestionar el avance del proyecto.');
INSERT INTO `mydb`.`rol` (`id_rol`, `name`, `description`) VALUES (3, 'Lector', 'Puede ver el progreso del proyecto a través de los diferentes módulos.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`estado`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`estado` (`id_estado`, `name`) VALUES (1, 'Por hacer');
INSERT INTO `mydb`.`estado` (`id_estado`, `name`) VALUES (2, 'En progreso');
INSERT INTO `mydb`.`estado` (`id_estado`, `name`) VALUES (3, 'Finalizada');

COMMIT;

